import { useEffect, useState } from "react";
import { Package } from "lucide-react";
import { getAdminOrders, updateOrderStatus } from "../services/orderService";
const paymentLabel = (method) => method?.startsWith("DEMO_") ? `Demo · ${method.slice(5).replaceAll("_", " ")}` : method || "Legacy";
export default function AdminOrders() {
    const [orders,setOrders]=useState([]); const [error,setError]=useState("");
    const load=async()=>{try{setOrders(await getAdminOrders());setError("");}catch(e){setError(e.response?.data?.message||"Could not load orders.");}};
    useEffect(()=>{load();},[]);
    const update=async(order,status)=>{try{await updateOrderStatus(order.id,status);await load();}catch(e){setError(e.response?.data?.message||"Could not update order.");}};
    return <main className="min-h-screen bg-[#f6f6f4] px-5 py-8"><div className="mx-auto max-w-7xl"><div className="mb-7 flex items-center gap-3"><Package size={38} className="text-[#111111]"/><div><h1 className="text-3xl font-bold text-[#111111]">All Orders</h1><p className="text-gray-600">Review and update platform orders.</p></div></div>
        {error&&<p role="alert" className="mb-4 rounded-xl bg-red-100 p-3 text-red-700">{error}</p>}
        <section className="mb-5 grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">Total orders <strong className="block text-2xl">{orders.length}</strong></div><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">Open <strong className="block text-2xl">{orders.filter(o=>!["Delivered","Cancelled"].includes(o.orderStatus)).length}</strong></div><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">Delivered <strong className="block text-2xl">{orders.filter(o=>o.orderStatus==="Delivered").length}</strong></div></section>
        <div className="overflow-x-auto rounded-2xl bg-white shadow"><table className="w-full text-left"><thead className="bg-[#111111] text-[#FFD21F]"><tr><th className="p-4">Order</th><th className="p-4">Buyer</th><th className="p-4">Product</th><th className="p-4">Seller</th><th className="p-4">Payment</th><th className="p-4">Amount</th><th className="p-4">Status</th><th className="p-4">Update</th></tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-b border-slate-200 transition hover:bg-amber-50/70"><td className="p-4">#{o.id}<div className="text-xs text-gray-500">{o.orderDate?new Date(o.orderDate).toLocaleDateString():""}</div></td><td className="p-4">{o.customerName}<div className="text-xs text-gray-500">{o.buyerEmail||"Legacy order"}</div></td><td className="p-4">{o.productName} × {o.quantity}</td><td className="p-4">{o.sellerEmail||"Unassigned"}</td><td className="p-4"><span className="font-semibold">{paymentLabel(o.paymentMethod)}</span><div className={`text-xs font-semibold ${o.paymentStatus==="PAID"?"text-emerald-700":"text-amber-700"}`}>{o.paymentStatus||"Not recorded"}</div></td><td className="p-4">₹{Number(o.totalAmount||0).toLocaleString("en-IN")}</td><td className="p-4">{o.orderStatus}</td><td className="p-4"><select value={o.orderStatus} onChange={e=>update(o,e.target.value)} className="rounded-lg border p-2">{["Placed","Processing","Shipped","Delivered","Cancelled"].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}{!orders.length&&<tr><td colSpan="8" className="p-8 text-center text-gray-500">No orders have been placed.</td></tr>}</tbody></table></div>
    </div></main>;
}
