import { useEffect, useState } from "react";
import { UserRound, Save } from "lucide-react";
import api from "../services/api";
import { useAuth } from "../context/AuthContext";
export default function BuyerProfile() {
    const {updateUser}=useAuth();
    const [profile,setProfile]=useState({name:"",email:"",phone:"",addressLine:"",city:"",state:"",pincode:"",paymentPreference:"COD"});
    const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
    useEffect(()=>{api.get("/buyer/profile").then(r=>setProfile({...profile,...r.data})).catch(e=>setError(e.response?.data?.message||"Profile could not be loaded.")).finally(()=>setLoading(false));},[]);
    const change=e=>setProfile({...profile,[e.target.name]:e.target.value});
    const save=async e=>{e.preventDefault();setSaving(true);setMessage("");setError("");try{const data=(await api.put("/buyer/profile",profile)).data;setProfile({...profile,...data});updateUser(data);setMessage("Profile and delivery details saved.");}catch(err){setError(err.response?.data?.message||"Could not save your profile.");}finally{setSaving(false);}};
    if(loading)return <main className="min-h-screen p-8">Loading your profile…</main>;
    return <main className="min-h-screen bg-slate-100 px-5 py-9"><form onSubmit={save} className="mx-auto max-w-3xl space-y-5 rounded-3xl bg-white p-6 shadow sm:p-9"><header className="flex items-center gap-3"><UserRound size={34} className="text-green-700"/><div><h1 className="text-3xl font-bold">My Profile</h1><p className="text-gray-600">Keep your contact and delivery details up to date.</p></div></header>{message&&<p className="rounded-xl bg-green-100 p-3 text-green-800">{message}</p>}{error&&<p role="alert" className="rounded-xl bg-red-100 p-3 text-red-800">{error}</p>}
        <label className="block font-semibold">Full name<input name="name" value={profile.name} onChange={change} required className="mt-1 w-full rounded-xl border p-3"/></label><label className="block font-semibold">Email address<input value={profile.email} readOnly className="mt-1 w-full rounded-xl border bg-gray-100 p-3"/></label><label className="block font-semibold">Phone<input name="phone" value={profile.phone} onChange={change} className="mt-1 w-full rounded-xl border p-3"/></label><label className="block font-semibold">Delivery address<textarea name="addressLine" value={profile.addressLine} onChange={change} className="mt-1 w-full rounded-xl border p-3" rows="3"/></label><div className="grid gap-3 sm:grid-cols-3"><label className="font-semibold">City<input name="city" value={profile.city} onChange={change} className="mt-1 w-full rounded-xl border p-3"/></label><label className="font-semibold">State<input name="state" value={profile.state} onChange={change} className="mt-1 w-full rounded-xl border p-3"/></label><label className="font-semibold">PIN code<input name="pincode" value={profile.pincode} onChange={change} className="mt-1 w-full rounded-xl border p-3"/></label></div><label className="block font-semibold">Preferred payment method<select name="paymentPreference" value={profile.paymentPreference||"COD"} onChange={change} className="mt-1 w-full rounded-xl border p-3"><option value="COD">Cash on delivery</option><option value="ONLINE">Online payment preference</option></select><span className="mt-1 block text-sm font-normal text-gray-500">Online payments are not processed in this version; no card details are stored.</span></label><button disabled={saving} className="rounded-xl bg-green-700 px-6 py-3 font-semibold text-white disabled:opacity-50"><Save className="mr-2 inline" size={18}/>{saving?"Saving…":"Save profile"}</button>
    </form></main>;
}
