import { useEffect, useState } from "react";
import { UserRound, Search, UserPlus, Trash2, Pencil } from "lucide-react";
import api from "../services/api";
export default function Customers() {
    const [users,setUsers]=useState([]);const [search,setSearch]=useState("");const [error,setError]=useState("");
    const [form,setForm]=useState({name:"",email:"",password:"",role:"BUYER"});
    const load=async()=>{try{setUsers((await api.get("/admin/users")).data);setError("");}catch(e){setError(e.response?.data?.message||"Could not load users.");}};
    useEffect(()=>{load();},[]);
    const add=async e=>{e.preventDefault();try{await api.post("/admin/users",form);setForm({name:"",email:"",password:"",role:"BUYER"});load();}catch(err){setError(err.response?.data?.message||"Could not create user.");}};
    const edit=async user=>{const name=window.prompt("Update name",user.name);if(name===null)return;const email=window.prompt("Update email",user.email);if(email===null)return;try{await api.put("/admin/users/"+user.id,{name,email});load();}catch(e){setError(e.response?.data?.message||"Could not update user.");}};
    const setRole=async(user,role)=>{try{await api.put("/admin/users/"+user.id,{role});load();}catch(e){setError(e.response?.data?.message||"Could not change role.");}};
    const setGstinStatus=async(user,gstinStatus)=>{try{await api.put("/admin/users/"+user.id,{gstinStatus});load();}catch(e){setError(e.response?.data?.message||"Could not update GSTIN review status.");}};
    const remove=async user=>{if(!window.confirm("Delete account for "+user.email+"?"))return;try{await api.delete("/admin/users/"+user.id);load();}catch(e){setError(e.response?.data?.message||"Could not delete user.");}};
    const visible=users.filter(u=>(u.name+" "+u.email+" "+u.role).toLowerCase().includes(search.toLowerCase()));
    return <main className="min-h-screen bg-[#f6f6f4] px-5 py-8"><div className="mx-auto max-w-7xl"><div className="mb-7 flex items-center gap-3"><UserRound size={38} className="text-[#b38a00]"/><div><h1 className="text-3xl font-bold text-[#b38a00]">Users and Roles</h1><p className="text-gray-600">Create accounts, edit details, and assign platform access.</p></div></div>
        {error&&<p role="alert" className="mb-5 rounded-xl bg-red-100 p-3 text-red-700">{error}</p>}
        <form onSubmit={add} className="mb-7 grid gap-3 rounded-2xl bg-white p-5 shadow sm:grid-cols-2 lg:grid-cols-5"><input aria-label="Name" placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="rounded-lg border border-slate-300 p-3 outline-none focus:border-[#d6a900] focus:ring-2 focus:ring-[#FFD21F]" required/><input aria-label="Email" type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="rounded-lg border border-slate-300 p-3 outline-none focus:border-[#d6a900] focus:ring-2 focus:ring-[#FFD21F]" required/><input aria-label="Temporary password" type="password" minLength="8" placeholder="Temporary password (8+ chars)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="rounded-lg border border-slate-300 p-3 outline-none focus:border-[#d6a900] focus:ring-2 focus:ring-[#FFD21F]" required/><select aria-label="Role" value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="rounded-lg border border-slate-300 p-3 outline-none focus:border-[#d6a900] focus:ring-2 focus:ring-[#FFD21F]"><option value="BUYER">Buyer</option><option value="SELLER">Seller</option><option value="ADMIN">Admin</option></select><button className="rounded-lg bg-[#FFD21F] p-3 font-bold text-[#111111] transition hover:bg-[#E8B900]"><UserPlus className="mr-1 inline" size={18}/>Create account</button></form>
        <div className="mb-4 flex items-center gap-2 rounded-xl bg-white p-3 shadow"><Search className="text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name, email, or role" className="w-full outline-none"/></div>
        <p className="mb-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Seller GSTIN and HSN review here is a manual admin record; the site is not connected to GSTN and cannot independently verify registrations.</p>
        <div className="overflow-x-auto rounded-2xl bg-white shadow"><table className="w-full text-left"><thead className="bg-[#111111] text-[#FFD21F]"><tr><th className="p-4">Name</th><th className="p-4">Email</th><th className="p-4">Role</th><th className="p-4">GSTIN / business state</th><th className="p-4">GSTIN review</th><th className="p-4">Actions</th></tr></thead><tbody>{visible.map(u=><tr key={u.id} className="border-b border-slate-200 transition hover:bg-amber-50/70"><td className="p-4">{u.name}</td><td className="p-4">{u.email}</td><td className="p-4"><select value={(u.role||"BUYER").toUpperCase()==="USER"?"BUYER":u.role} onChange={e=>setRole(u,e.target.value)} className="rounded-lg border border-[#d6a900] bg-amber-50 p-2 font-semibold text-slate-800 focus:ring-2 focus:ring-[#FFD21F]">{["BUYER","SELLER","ADMIN"].map(r=><option key={r}>{r}</option>)}</select></td><td className="p-4 text-sm">{u.role==="SELLER"?<><div>{u.gstin||"Not submitted"}</div><div className="text-xs text-slate-500">{u.state||"Business state not set"}</div></>:"—"}</td><td className="p-4">{u.role==="SELLER"?<select value={u.gstinStatus||"NOT_SUBMITTED"} onChange={e=>setGstinStatus(u,e.target.value)} className="rounded-lg border p-2 text-sm">{["NOT_SUBMITTED","PENDING","VERIFIED","REJECTED"].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select>:"—"}</td><td className="p-4"><div className="flex gap-2"><button onClick={()=>edit(u)} title="Edit user" className="rounded-lg bg-[#FFD21F] p-2 text-[#111111] transition hover:bg-[#E8B900]"><Pencil size={18}/></button><button onClick={()=>remove(u)} title="Delete user" className="rounded-lg bg-red-600 p-2 text-white"><Trash2 size={18}/></button></div></td></tr>)}{!visible.length&&<tr><td colSpan="6" className="p-8 text-center text-gray-500">No matching users.</td></tr>}</tbody></table></div>
    </div></main>;
}
