import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, Package, CalendarDays, Phone, MapPin, ChevronRight } from "lucide-react";
import { getMyOrders } from "../services/orderService";
import { resolveProductImage } from "../services/resolveProductImage";
import lenovoImage from "../assets/lenovo-loq-rtx5050.png";
const paymentLabel = (method) => method?.startsWith("DEMO_") ? `Demo · ${method.slice(5).replaceAll("_", " ")}` : method || "Legacy order";
function MyOrders() {
    const [orders,setOrders]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
    useEffect(()=>{let active=true;getMyOrders().then(data=>{if(active)setOrders(data);}).catch(e=>{if(active)setError(e.response?.data?.message||"Orders could not be loaded.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
    return <main className="min-h-screen bg-slate-100 px-5 py-10"><div className="mx-auto max-w-6xl"><Link to="/" className="mb-6 inline-flex items-center gap-2 font-semibold text-[#6f5500]"><ArrowLeft size={20}/>Back to Home</Link><h1 className="mb-8 flex items-center gap-3 text-4xl font-bold text-[#6f5500]"><Package size={34}/>My Orders</h1>
        {error&&<p role="alert" className="mb-5 rounded-xl bg-red-100 p-3 text-red-700">{error}</p>}
        {loading?<div className="space-y-5" role="status" aria-label="Loading orders">{[1,2].map((item)=><div key={item} className="flex flex-col gap-5 rounded-3xl bg-white p-5 shadow sm:flex-row"><div className="skeleton-shimmer h-32 w-full rounded-xl sm:w-32"/><div className="flex-1"><div className="skeleton-shimmer h-6 w-2/3 rounded"/><div className="skeleton-shimmer mt-4 h-4 w-1/3 rounded"/><div className="skeleton-shimmer mt-4 h-4 w-1/2 rounded"/><div className="skeleton-shimmer mt-5 h-4 w-3/4 rounded"/></div></div>)}</div>:orders.length===0?<div className="rounded-3xl bg-white p-10 text-center"><Package size={55} className="mx-auto mb-3 text-gray-400"/><h2 className="text-2xl font-semibold">No Orders Yet</h2><p className="mt-2 text-gray-500">Your purchases will appear here.</p><Link to="/" className="mt-5 inline-block rounded-xl bg-[#FFD21F] px-7 py-3 text-[#111111] hover:bg-[#E8B900]">Shop Now</Link></div>:<div className="space-y-5">{orders.map(o=><Link key={o.id} to={`/my-orders/${o.id}`} className="group block rounded-3xl bg-white p-5 shadow transition hover:-translate-y-0.5 hover:shadow-lg focus:outline-none focus:ring-2 focus:ring-[#d4a900] sm:p-6"><div className="flex flex-col gap-5 sm:flex-row"><img src={resolveProductImage(o.productImage)||lenovoImage} onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src=lenovoImage;}} alt={o.productName} className="h-32 w-full shrink-0 rounded-xl border bg-gray-50 object-contain p-2 sm:w-32"/><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><h2 className="text-xl font-bold text-[#6f5500] sm:text-2xl">{o.productName}</h2><span className="h-fit rounded-full bg-[#fff0a8] px-4 py-2 text-sm font-semibold text-[#6f5500]">{o.orderStatus}</span></div><p className="mt-2">Quantity: {o.quantity} · ₹{Number(o.productPrice||0).toLocaleString("en-IN")}</p><p className="mt-2 text-lg font-bold text-[#6f5500]">Total: ₹{Number(o.totalAmount||0).toLocaleString("en-IN")}</p><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-sm">Payment: {paymentLabel(o.paymentMethod)}</span><span className={`rounded-full px-3 py-1 text-sm font-semibold ${o.paymentStatus==="PAID"?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-800"}`}>{o.paymentStatus||"Payment status unavailable"}</span></div><p className="mt-2 flex items-center gap-2 text-gray-600"><CalendarDays size={16}/>{o.orderDate?new Date(o.orderDate).toLocaleString("en-IN"):"Date unavailable"}</p><p className="mt-3 flex items-center gap-2 text-gray-600"><Phone size={16}/>{o.phone}</p><p className="mt-1 flex items-start gap-2 text-gray-600"><MapPin size={16} className="mt-1"/>{[o.address,o.city,o.state,o.pincode].filter(Boolean).join(", ")}</p><span className="mt-4 inline-flex items-center gap-1 font-semibold text-[#725700]">View order details <ChevronRight size={18} className="transition group-hover:translate-x-1"/></span></div></div></Link>)}</div>}
    </div></main>;
}
export default MyOrders;

